### ISSUE TITLE
List name syntax does not match download syntax

### ISSUE THREAD

**Issue by 3dsf** [intx82/a9-v720#1]
Thanks for the effort you've already put into this project.

Could you make it so when the list name syntax matches the download name syntax?
Below is an example showing that using the name without the dashes, does not work.

---

`python3 src/a9_naxclow.py -f`

> Found A9 camera, FW version: 202212011602
> Files @ 20230210:
> 		-05:06: Filename: 202302100506, Size: 17304244
> 		-05:07: Filename: 202302100507, Size: 16146476
> 		-05:08: Filename: 202302100508, Size: 14613284
> 		-05:09: Filename: 202302100509, Size: 13289740
> 		-05:11: Filename: 202302100511, Size: 10305624
> 		-05:15: Filename: 202302100515, Size: 10112652
> 		-05:16: Filename: 202302100516, Size: 15105012
> 		-05:17: Filename: 202302100517, Size: 12174800
> 		-05:18: Filename: 202302100518, Size: 10620000

`python3 src/a9_naxclow.py -d 202302100518 -o out.avi`

> Found A9 camera, FW version: 202212011602
> File 202302100518-22-18 not found

`python3 src/a9_naxclow.py -d 20230210-05-18 -o out.avi`

> Found A9 camera, FW version: 202212011602
> Found file @ 20230210 5 18 : 202302100518  with size: 10620000
> 10.1MB [00:32, 322kB/s]

**Comment by intx82** [comment]
Done, check it please
