### ISSUE TITLE
Live video streaming issue

### ISSUE THREAD

**Issue by madix30git** [intx82/a9-v720#10]
Hello intx82!

Thank you in advance for your contribution in the development of software for alternative management of A9 mini cameras with BL7252 MCU.
I recently acquired some units and after some tests, I was interested in alternatively accessing the V720 app on my local network. In this way, I found your contribution through search engines.
I would like to ask for your help.
The units I purchased have firmware number 202302031142. The following commands work:

"python3 src/a9_naxclow.py -f" receives the list of .avi files contained in the memory card.

"python3 src/a9_naxclow.py -d 202301312016 -o out.avi" I download the specified file that is on the card (according to the file name).

However, when running the command "python3 src/a9_naxclow.py -l -o live.avi -r -i", a window opens (supposedly streaming the video from the camera) and turns gray. Does not display camera frames.
Obs.: I noticed that the generated live.avi file remains with 0Kb. Except at the end of the execution, the file has its real size and it is possible to play it in a player.
I ask you to help me with information and even instructions on how I can proceed to correct it.
Thank you again!
I count on your help!

**Comment by intx82** [comment]
Hello
Yesterday i received cameras with the same version as yours and live video works in AP mode, try to remove `-r -i` and add `-v`

Does it throw any exception?

**Comment by madix30git** [comment]
No. No exception.
I was able to get the stream by adding the code "cv2.waitKey(1)" after line 35 of the file "a9_live.py" as shown in the image.

I also did the BGR to RGB color correction by changing line 35 like this:
"cv2.imshow('Frame', last_img[:,:,::-1])#Converts from BGR to RGB"

I'm getting streaming normally for now.

Thank you very much for your attention!

![2](https://user-images.githubusercontent.com/129349213/228741950-08bbb0e4-3cbe-4608-b707-0a1cc6e1447f.jpg)
![3](https://user-images.githubusercontent.com/129349213/228741953-38036647-5b8a-4d1e-aade-52afdff77fe4.jpg)

**Comment by intx82** [comment]
This is a very strange, seems you have a different OpenCV version and that may lead to this issue

Also, there is a fork https://github.com/froloffw7/a9-v720 where OpenCV has been replaced with FFmpeg, it could be more suitable for you

And maybe in a near feature i will move from OpenCV to the same model as in `fake-server` mode, where MJPG stream is used

Close please the issue if you don't have problem anymore

**Comment by madix30git** [comment]
I will be studying this fork.
Success for you!
