### ISSUE TITLE
Live stream stops when I try to run 2 cameras simultaneously

### ISSUE THREAD

**Issue by chiragd03** [intx82/a9-v720#11]
The script runs perfectly for one camera, but when i try to connect another camera to the same AP, i see that the code provides with a live stream url for second camera but as soon as i browse the live stream link for the second camera, it doesn't work and even stops the stream for the first camera

**Comment by intx82** [comment]
Hello
Could you please add '-v' argument to script and attach logs here? 

This could happen if cameras have the same ID. Better to check logs first, anyway, simultaneous work of a three camera in same time has been tested, and they work with the latest commit

There is another bug which annoying me, I have at home 2 cameras, and sometimes they lost the connection to the server script, while cameras think that they are connected. I think i will fix this in the near future.

**Comment by chiragd03** [comment]
My apologies for the delayed reply. I executed the command "python a9_naxclow.py -s -v" and have attached the logs here:
https://gist.github.com/chiragd03/6a02ad4c2561bc4523b1e6be546d274c

I initiated the script and connected the first camera, successfully opening its live stream in the browser. However, when I connected the second camera and attempted to open its live stream, the first camera's live stream froze (no movement in the browser), and I was unable to view anything for the second camera in the browser.

I hope my explanation was clear. For your reference, I've attached screenshots of both live streams in the browser:

https://drive.google.com/file/d/1syL4ej3KeYTtVRNXEfL0Gr2kBoNvjvqg/view?usp=sharing

**Comment by intx82** [comment]
Are you starting the server over NAT (ie over gateway, server and cameras locates in different networks?)

```
cam1 ---|
        |  ---> router ---> internet  ---> server
cam2 ---|
```

I see that yours cameras use the same IP address (192.168.2.105) and this lead to this issue, i will check what i can do.

**Comment by chiragd03** [comment]
I am using my Windows 11 machine(192.168.2.105) to host the hotspot, run mosquito broker and run the server script. Also, I have redirected v720.naxclow.com and v720.p2p.naxclow.com to 192.168.2.105. Both the cameras connect to this Windows machine.  Did I mess up something?

**Comment by chiragd03** [comment]
Yes, I think that is the case. This is the ipconfig result
https://gist.github.com/chiragd03/2c0d7fe4f9c4ac2ece753538a8f8702c
I think the hotspot is Wireless LAN adapter Local Area Connection* 10 : with IPv4 Address. . . . . . . . . . . : 192.168.137.1(Preferred)

Also attached is the ip for both the cameras attached to the hotspot
https://drive.google.com/file/d/10z6GkhgxvJ8_LHSxVUeC6xO1W-RK184G/view?usp=sharing

**Comment by intx82** [comment]
Set DNS redirect to 192.168.137.1, this should helps

**Comment by chiragd03** [comment]
Sorry, but where do I set the redirect and from where ?

**Comment by intx82** [comment]
In yours DNS server. ie:

```
v720.naxclow.com - A - 192.168.137.1
p2p.v720.naxclow.com - A - 192.168.137.1 
v720.p2p.naxclow.com - A - 192.168.137.1
```

Even if relative to your's home router network is unavailable, this should work.

The other way, you may use something like `tftpd64` (https://pjo2.github.io/tftpd64/) to configure DNS server for hotspot interface.
The main goal - eliminate NAT between application and cameras

**Comment by chiragd03** [comment]
Still not working :( 
I am using Pi-hole on my network to set local DNS records. My windows machine is using Pi-hole as DNS Server. Now when i do nslookup to v720.naxclow.com from any device connected to my network or even to the hotspot , I get 192.168.137.1 (After making above change ). I have attached a screen recording of the issue just in case i missed something

https://drive.google.com/file/d/1lH9ViNe7vHieV59pvJZSZFB_SZL8wQdG/view?usp=sharing

As soon as i browse the second stream, the first one also freezes

**Comment by intx82** [comment]
Ok, i have some ideas how to fix it in code, but this would be not fast.

If in short, due to camera use both UDP and TCP channels, they should be attached to the same camera object and right now this is done via comparing of incoming IP, if it is the same - then this is the same camera (i.e. the same object)

In your case (as well as in any NAT case) you have the same camera's IP, so comparing on the second camera is failing and this lead to broken connection on the both cameras. (On a first connection will be replaced, on a second it will be missed)

**Comment by chiragd03** [comment]
Just a quick update, I ran the same code in Linux Mint OS and it worked perfectly fine. Looks like a windows thing maybe ?

**Comment by intx82** [comment]
Maybe, i will check. Windows sockets work a little bit different, this could be.

**Comment by intx82** [comment]
Ok, i have solved yours issue, you may try to use.
