### ISSUE TITLE
Why it was needed? I just purchased one but not confident to use it or not because of Privacy concern

### ISSUE THREAD

**Issue by hanzlahabib** [intx82/a9-v720#12]
Why it was needed? I just purchased one but not confident to use it or not because of Privacy concern

**Comment by intx82** [comment]
The purpose of this project is closing own requirements, you may use it as you want for yours purposes, inside code I didn't collect any private information. 

Related to my requirements, I want to see what's happens in my house (really, what do my cats :) ) and write the capture to own home server. (this could be done via ffmpeg with outgoing mjpg stream).

About Chinese side and original app. I can't say about you, but me is not so very important person for whom should spying in 24/7. 
Also, to spying they have a lot of different tools, for example simple statistic in facebook/tiktok which after shows to you targeted adverts. Take also in option that to spy on you, someone (GOV/ORG/*) should pay for a incoming traffic and procesor time and space on the disk. Chinese guys prefer to make a direct bridge between yours camera and application, but if this couldn't be done - they redirect video stream over the own server. So technically they can spy, but i don't think they do this. 

Better to show you a target advert in their app and make some money.
