### ISSUE TITLE
After shut off/on of the camera the connection is lost after some time

### ISSUE THREAD

**Issue by vale-max** [intx82/a9-v720#13]
Hello intx82,
I'm using your fake server and noticed that if I shut down the camera then switch it back on after a short time the server says that the camera drops the connection after few seconds as it detects the previous TCP connection is cut.
e.g.:
I start the server and connect the camera:
```
python3 src/a9_naxclow.py -s
-------- A9 V720 fake-server starting. --------
Device list: http://127.0.0.1/dev/list
Live capture: http://127.0.0.1/dev/[CAM-ID]/live
Snapshot: http://127.0.0.1/dev/[CAM-ID]/snapshot

-------- Found device 0800c0098970 --------
Live capture: http://127.0.0.1/dev/0800c0098970/live
Snapshot: http://127.0.0.1/dev/0800c0098970/snapshot
```
Now it is connected to port 30643
`[{"host": "192.168.110.159", "port": 30643, "uid": "0800c0098970"}]`

Now I switch the camera off by long press of off button and get the switch off MQTT message:
`Naxclow/P2P/Users/Device/Status {"device":"0800c0098970","token":"NAXCLOW","status": 0}`

Then I switch it back on and the server "sees" it again:
```
-------- Found device 0800c0098970 --------
Live capture: http://127.0.0.1/dev/0800c0098970/live
Snapshot: http://127.0.0.1/dev/0800c0098970/snapshot
```
This time is on port 40498
`[{"host": "192.168.110.159", "port": 40498, "uid": "0800c0098970"}]`
 
However the server after some seconds tries to communicate again on the old port, gets a connection reset and interprets it as the new connection being severed, outputs the following message and removes the camera from the list of the available cams:
```
2023-04-17 23:44:19,316  [  ERROR] [TCP-CON 192.168.110.159:30643] Connection closed by peer (camera @ ('192.168.110.159', 30643))
2023-04-17 23:44:19,316  [  ERROR] [TCP-CON 192.168.110.159:30643] Connection closed: ('192.168.110.159', 30643)
-------- Device 0800c0098970 has been disconnected --------
```

Possible solutions now are either restarting the server if the camera is switched on/off, or waiting the "connection closed" message before switching it back on, but it would be nice if the server could understand the camera is switched off from the MQTT message and forget immediately about the old connection, or check if there's a new connection to the same camera before deciding the connection is closed and remove it from the list of available cams.

**Comment by intx82** [comment]
Could you please run it with argument '-v' and attach logs somewhere? Thanks

**Comment by vale-max** [comment]
Here you have it

[verbose.log](https://github.com/intx82/a9-v720/files/11277253/verbose.log)

**Comment by intx82** [comment]
ok, clear, it's the same issue as #11
