### ISSUE TITLE
Feature request: option to change the port number

### ISSUE THREAD

**Issue by vale-max** [intx82/a9-v720#14]
Hello, me again,
I use your fake server behind a nginx reverse proxy.
It works seamlessly on port 9900, but to move it I had to change the HTTP_PORT variable in fake_srv.py and in v720_http.py

Would be nice to have it as a command option.

BTW, my camera streams an MJPEG vid at 640x480
Is this the max it can do? The data sheet speaks of H.264 at FullHD...

**Comment by intx82** [comment]
There is no HD in camera, only MJPG on 640x480.
Related to port, i will add an argument to code, but you may use it only with proxy, because this can't be configured on camera side.

**Comment by vale-max** [comment]
That's why I need it. In my network I use a raspberry with nginx which is dedicated to serve a number of different things through http so I can't leave port 80 for the camera only, luckily works smoothly reverse-proxying it.

**Comment by intx82** [comment]
Try to use argument `--proxy-port` 

Example:

```
python3 src/a9_naxclow.py -s --proxy-port 8080
```
