### ISSUE TITLE
Feature request: Add audio stream to http output

### ISSUE THREAD

**Issue by ewqstar** [intx82/a9-v720#17]
Hello. If possible, add audio stream to http output, like http://[FAKE_SRV_IP]/dev/[CAM_ID]/audio

**Comment by intx82** [comment]
Hi
it's possible, at least I can pack incoming g711 (wav) stream to HTTP, but I don't know will it be supported by browser

**Comment by dbuezas** [comment]
The two streams can be merged into a single rtsp stream by go2rtc, so it would be useful indeed :)

**Comment by dbuezas** [comment]
I'm almost done with this. A bit rough on the edges but vlc can play it live already

**Comment by dbuezas** [comment]
I managed to add an extra endpoint that generates an output stream with audio. Go2rtc can read it well and it seems to ve quite stable. I'm using ffmpeg and named fifo queues instead of opencv, so the addon should run in alpine. Less ram and whatnot.
I also finally understood how to send commands via udp without an mqtt server, so the add on will also expose those.

**Comment by dbuezas** [comment]
Expose devices from add-on

**Comment by dbuezas** [comment]
Here's the relevant code. I'll make a pr to this repo with only this addition if the author wishes for that.
https://github.com/dbuezas/a9-camera-ha-add-on/blob/main/rootfs/usr/local/a9-v720/src/v720_http.py#L73-L166

In the meanwhile, if you intended to use it with home assistant, see the readme of this repository.

**Comment by intx82** [comment]
@dbuezas thanks, you do a lot of work, could you please do a pull-request

I was not sync with you, anyway, issue may be closed, master branch now also support audio.
Use `http://[srv-ip]/dev/[dev]/audio` link.

Example of usage: 

```
ffmpeg -i http://127.0.0.1/dev/0800c0011001/audio -r 10 -i http://127.0.0.1/dev/0800c0011001/video out.avi
```

**Comment by ewqstar** [comment]
Thanks for your work!
