### ISSUE TITLE
Running inside a home assistant add on

### ISSUE THREAD

**Issue by dbuezas** [intx82/a9-v720#18]
Hi!
I'm trying to run the fake server inside a home assistant add on, and building a docker image with opencv-python in it is proving quite hard.
* Have you considered using something else instead of opencv?
* Any tips on building a small docker container with opencv-python built in?

I tried to base on one of [these](https://github.com/gigante/python-opencv) but the addon would just not start.

**Comment by dbuezas** [comment]
Ok, it seems like using alpine was a very bad idea. 
I got it to run with a debian base.

**Comment by acseven** [comment]
@dbuezas Would you mind sharing the docker configuration files you’re using?

**Comment by dbuezas** [comment]
Sure, I'll put upload the addon soon. I still need to expose reasonable ports and some other minor details.

I'd like to add some mqtt commands too to turn the IR light on/off, and use ffmpeg instead of opencv. But that will take a bit longer.

**Comment by dbuezas** [comment]
<img width="872" alt="image" src="https://github.com/intx82/a9-v720/assets/777196/eeeec5de-f05b-450c-8731-7d76e6e73f41">
It looks like it is working
