### ISSUE TITLE
Streaming from cam to app

### ISSUE THREAD

**Issue by GermanDZ** [intx82/a9-v720#3]
# Handshake for streaming with Naxclow server

I've setup Wireshark over a dedicated WIFI connection and dumped the communications between the mobile app, the cam and the servers

## Communication

The cam was already registered in the app (with naxclow server) and the app connected to the server.

I've started the transmission from the app and this is the description of what happened.

### Nodes

APP: local ip addr 192.168.2.14 (private ip address of the mobile phone with the v720 app)
CAM: local ip addr 192.168.2.13 (private ip address of the camera)
STREAM: ip addr 43.240.74.95 (the remote "streaming" server, `host` returned by `v720.naxclow.com` in endpoint `/getA9ConfCheck`)
(a.b.c.d is my public ip address in internet, my home internet router WAN ip)

### "Channels"

port 29942: the `tcpPort` returned by `v720.naxclow.com` in endpoint `/getA9ConfCheck`

APP-to-STREAM-TCP: APP TCP (port 51733) to STREAM on port 29942
APP-to-STREAM-UDP: APP UDP (port 58763) to STREAM on port 29942
STREAM-to-CAM-TCP: STREAM TCP (port 29942) to CAM on port 13761
APP-to-CAM-TCP: APP UDP (port 58763) to CAM on port 18297

### Sequence of messages

`devTarget`, `devToken`, `cliTarget`, `cliId` and `target` are redacted.

APP-to-STREAM-TCP:
{"cliNatPort":51733,"devTarget":"0800c000XYZW","code":10,"cliPort":45426,"cliIp":"a.b.c.d","devToken":"XJ0af899","cliNatIp":"192.168.2.14"}
{"code":100,"uid":"0003fb965495XXXXYYYYXZZ618febAB","domain":"v720.naxclow.com","token":"55ABfb77"}

APP-to-STREAM-UDP:
{"code":20} #  (UDP hole-punch?)

APP-to-STREAM-TCP:
{"cliNatPort":51733,"devTarget":"0800c000XYZW","code":10,"cliPort":45426,"cliIp":"a.b.c.d","devToken":"XJ0af899","cliNatIp":"192.168.2.14"}

STREAM-to-CAM-TCP:
{"code":11,"cliTarget":"0003fb965495XXXXYYYYXZZ618febAB","cliToken":"55ABfb77","cliIp":"a.b.c.d","cliPort":45426,"cliNatIp":"192.168.2.14","cliNatPort":51733}

STREAM UDP (port 29942) to CAM on port 18297:
{"code":21,"ip":"a.b.c.d","port":45412}

APP-to-CAM-TCP:
{"code":50,"cliToken":"55ABfb77","devTarget":"0800c000XYZW","cliId":"0003fb965495XXXXYYYYXZZ618febAB","devToken":"XJ0af899"}

APP-to-STREAM-TCP:
{"code":52,"status":1,"devTarget":"0800c000XYZW","devToken":"XJ0af899"}

STREAM-to-CAM-TCP:
{"code":53,"target":"0003fb965495XXXXYYYYXZZ618febAB","status":1}

APP-to-STREAM-TCP:
{"target":"0800c000XYZW","content":{"code":298},"code":301}

APP-to-CAM-TCP:
{"timeStamp":"1676971368690","code":54}

STREAM-to-CAM-TCP:
{"code":301,"target":"0003fb965495XXXXYYYYXZZ618febAB","content":{"code":298}}

APP-to-STREAM-TCP:
{"target":"0800c000XYZW","content":{"unixTimer":1676974968,"code":4},"code":301}

STREAM-to-CAM-TCP:
{"code":301,"target":"0003fb965495XXXXYYYYXZZ618febAB","content":{"unixTimer":1676974968,"code":4}}

APP-to-STREAM-TCP:
{"target":"0800c000XYZW","content":{"code":3},"code":301}

APP-to-CAM-TCP:
{"timeStamp":"1676971370691","code":54}

STREAM-to-CAM-TCP:
{"code":301,"target":"0003fb965495XXXXYYYYXZZ618febAB","content":{"code":3}}

The CAM sent 1024 bytes UDP packets from port 18297 to APP (port 58763) during the transmission,
and the APP "responded" UDP 72 bytes packets.

**Comment by intx82** [comment]
Hi

I have a time to continue my experiments, and stuck between points with 'code': 51/50 and updating time on code: 54.
There should be sent something else from server. Could you please share with me (in telegram or there) yours cap file

On code 50, server sends a request to UDP-CLI to check is current network setting is acceptable or not, after on UDP-SRV or TCP channel server should send something to enable further transmissions, but it's not happens.

Also found that in yours logs, 'code': 54 have an argument **timeStamp** while in naxclow sources it had a name **timerStamp**

Currently, my experiments located in 'fake_srv_exp' branch. It's a non-understandable mess of code, but may be interested to someone

------
```Logs
running..
REQ: /app/api/ApiServer/getA9ConfCheck?devicesCode=0800c0012345&random=FGHIJK&token=5f42d1278b
HTTP/1.1 200
Server: nginx/1.14.0 (Ubuntu)
Date: Fri, 10 Feb 2023 22:29:57 GMT
Content-Type: application/json
Content-Length: 215
Connection: keep-alive

{"code":200,"message":"操作成功","data":{"tcpPort":6123,"uid":"0800c00128F8","isBind":"8","domain":"v720.naxclow.com","updateUrl":null,"host":"10.42.0.1","currTime":"1676097689","pwd":"91edf41f","version":null}}

[TCP] Connected by ('10.42.0.28', 17832)  @ port 6123
[TCP] JSON recv: [107]: {
    "code": 100,
    "uid": "0800c0012345",
    "token": "91edf41f",
    "domain": "v720.naxclow.com"
}
[TCP] Found device: 0800c0012345 token: 91edf41f
[TCP] Send respone as OK: {'code': 101, 'status': 200}
Next step @ rcv: set_nat
Curr step: set_nat
[TCP] Send status req: {'code': 11, 'cliTarget': '00112233445566778899aabbccddeeff', 'cliToken': '55ABfb77', 'cliIp': '10.42.0.1', 'cliPort': 53221, 'cliNatIp': '10.42.0.1', 'cliNatPort': 41234}
Next step @ fsm1: -
[UDP-SRV] JSON recv: [32]: @ 6123 port { 
    "code": 20
}
[UDP-SRV] Send UDP response: {'code': 21, 'ip': '10.42.0.1', 'port': 53221}
[TCP] JSON recv: [204]: {
    "code": 12,
    "status": 200,
    "devIp": "10.42.0.1",
    "devPort": 53221,
    "devNatIp": "10.42.0.28",
    "devNatPort": 30279,
    "cliTarget": "00112233445566778899aabbccddeeff",
    "cliToken": "55ABfb77"
}
[UDP-CLI] Heartbeat, sending response 
[UDP-SRV] Heartbeat, sending response
[UDP-CLI] JSON recv: [76]: {
    "code": 51,
    "devTarget": "0800c0012345",
    "status": 200
}
[UDP-CLI] JSON recv: [76]: {
    "code": 51,
    "devTarget": "0800c0012345",
    "status": 200
}
[UDP-CLI] Send status req: {'code': 50}
[UDP-CLI] JSON recv: [76]: {
    "code": 51,
    "devTarget": "0800c0012345",
    "status": 200
}
[UDP-CLI] JSON recv: [76]: {
    "code": 51,
    "devTarget": "0800c0012345",
    "status": 200
}
[UDP-CLI] Send status req: {'code': 50}
[UDP-CLI] JSON recv: [76]: {
    "code": 51,
    "devTarget": "0800c0012345",
    "status": 200
}
[UDP-CLI] JSON recv: [76]: {
    "code": 51,
    "devTarget": "0800c0012345",
    "status": 200
}
[UDP] Send baseinfo req: {'code': 301, 'target': '00112233445566778899aabbccddeeff', 'content': {'code': 298}}
[TCP] Recv [20]: 100
[TCP] Heartbeat, sending response
Next step @ rcv: -
[TCP] Recv [20]: 100
[TCP] Heartbeat, sending response
Next step @ rcv: -
[TCP] Recv [20]: 100
[TCP] Heartbeat, sending response
Next step @ rcv: -
[TCP] Recv [20]: 100
[TCP] Heartbeat, sending response
Next step @ rcv: -
[TCP] Recv [20]: 100
[TCP] Heartbeat, sending response
Next step @ rcv: -


```

**Comment by intx82** [comment]
Fake server is ready to use, give me feedback, maybe together we can do more
