### ISSUE TITLE
Version for HDWifiCamPRo

### ISSUE THREAD

**Issue by valexi7** [intx82/a9-v720#6]
Hi,

Some of these cameras use HDWifiCamPro application to see the feed. Can you develop a version for these also?
https://play.google.com/store/apps/details?id=com.shix.qhipc&hl=en_US

**Comment by intx82** [comment]
Hi
i don't have such camera to test, but i would be appreciated if you left here a link where to buy it. 

Decompiled sources of `com.shix.qhip` looks understandable, and which is more interesting seems camera have json protocol which is easy to repeat

**Comment by NegativeIAmAMeatPopsicle** [comment]
I have 4 of these alternate cameras.  I've opened up two and I have seen boards:

HB6_V1.0D211125 (photographed below)
and
HB6_V1.1D220607

Looks like only a single UART on this version versus the version currently being studied.  The differences I can see on the V1.1 board is that Q2, Q5, R14, R16, R20 and R23 are populated.

Very, very new to this but I should have the tools to help out.  I have a USB-to-TTL dongle, a rudimentary ability with Python, a couple of Linux machines and Raspberry Pis, a soldering station, and some time.

Let me know if you would like me to help out - I'll just need more explicit instructions than an average user here.

![A9_hb6_v1 0D211125_camera_side](https://user-images.githubusercontent.com/128076117/225700900-52c09fbf-18ae-4d4a-9c2d-414b7a062afc.JPG)
![A9_hb6_v1 0D211125_chip_side](https://user-images.githubusercontent.com/128076117/225700912-d4bd898c-b9c8-4a65-8b99-b564276ff6b2.JPG)

**Comment by intx82** [comment]
Looks very similar, try to connect UART (rx/tx pins on a second photo) and log with miniterm incoming messages. This will help me a lot. 

Also in issue #7 (https://github.com/intx82/a9-v720/issues/7#issuecomment-1465388206) has been pointed useful links which may works on your camera.
